before_install:
- chmod 777 cd/before-deploy.sh
- cd/before-deploy.sh
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.yarn-cache"
  - "$HOME/.sonar/cache"
language: java
install: true
jdk:
- openjdk8
- openjdk9
- openjdk10
- openjdk11
- openjdk12
- openjdk13
stages:
- test
- deploy
addons:
  sonarcloud:
    organization: joquijada-github
jobs:
  include:
  - stage: test
    name: Test the Code
    script: mvn clean package -P coverage sonar:sonar
    if: type IN (push, pull_request)
  - stage: deploy
    name: Deploy to Maven Repo
    script:
    - yarn global add https://github.com/conveyal/maven-semantic-release.git#e5551beb4ec266bb520ae5ff155bc0d04acf8f05
      semantic-release@15
    - mvn package -Dmaven.test.skip=true
    - semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release
      --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release
      --verify-release @conveyal/maven-semantic-release --use-conveyal-workflow
    if: branch = master
sudo: false
env:
  global:
  - secure: OkHAS8OkvM9mr/Eaouy55OJcR+jITD6egMk67YUZXoD4J8hrvBFkyjt/rDjY/KoRt2UoflrgIdB7PWsFWF4WVO1V5IZNLOhuIGJHwftd75PcnALAwh1EIMxWgT61t/KESRPr0DJAf3Mg0aDyZZ7VYAq7vLL+krwiMtK+dRVZ1PEad3SXCzw5h0yF9+uzAlktkpXRXaQVWZfTshUbDUVXvZG0lmgpvIKlxqaGJC7itgUW1KCZjRV4LYr5DJjeu27sZUihczkAd3d2u6hAJCJHG7E2JHNstI5lGBR0aG7Heg8xbHowq4kWrMa74IEmP5dHs6WTeCnJR2l0Rs09scKS0Zgo41qvcw2ybKZIYmvxNDVyLWOEOWk4Hz8GPYsweTL54NedW2FB++Xx40EBmJAYc8iIC12Qq2VRz/irXnCxpcJ0zNo/O+Acri87pxu9qQf1IKoyVgc22qN6A04Np4aNOOf6Se5OLLrbLCfB9LgP5lyqB/1rZXIzGLmzK54tO7UFsXvVQbS8YZvaORIYbpuF45+RG5BpbLiL7XGQGmFOZ8OXS25viS8YSOOMSxHx6f48WnEMq8Rhm+8yIy4W4iits6HULuFUcJJQ1DhrOFIHmBn2NQzEtdZrO6ex37dHhnhzm9E4FaCQP7YdDpfCPTKbJKPEZnAClIkWh2NvYnwylCA=
  - secure: pd0isqJH4IDNti+bRQkqhJ6H6uHDIbxyZOTFyOsf04cQOVNYsP9KHH+xDm170Fi34/8twwylkb+oxTvP3EFZxJVupZAo9Dwe78TsZ0isiosxu5kedctrcTGS+IUPD0wjP7gguEnFFM6ARXqCZqbJudwseR0HSjODKrx1qTA1JSdC4/VhM/Jh5OTlzGqkZURyWY6oDuModfLSV7lqRXTkV9QDoTGXPue0LD0hDlBzwJnFrNJCtZaIqa+oWBMfrA7PVVWmXAjN9aus9IXM9A6r5gsN7GVk2K7K7qhK+KGXcAYYc8Zno3nHYRwSB/G7wlh7+uGE+EJ33oloMPlvu2WHgNUrOSEACyIWMrzXpFsjxDtK0W22Xf/Dmg+vmaJGGeEUkdUPv/8z39Ei4KH3FMOlvX2YtTpIqGGBxD4bzSU1jlO3pYQvuz+0T9YALYUOsQc3e+lhBED8AsYRLuukOorWuEkcp9HMphL9IACn4cFlzfQrfLPfGCHagRJHoxm8XWrocYIu7mOpBDtqTghOhNMQfefyvEyTscCF1EEyV1y/FSLgu5J4voz89VWuMNpAWVejpRbWGG/uLQVnbjnUd6kj4ZUZMtfqG/iPkUBk1AYBnfPHloONAghx6sUqsLxIwSUHeqNjrXzGu1pWU5GeTWKDLoAAprjgBbQH5a5+xOQIeJM=
  - secure: PCCIjzGi4kKTWiI7IZxPYgdYUnrfZbKdEjVw7EvlOz5ZgDYVPbDXk2XHMRhGhJ5xf1H42Icza5vkg66eirtEAGVmEqDcg9O8lGDaVF+5UrzKGbcNdqcEXbUYrf6Vlgr1PfSs+Qw53nK4gf43SfRcLhPJE4BvehivkXo6T8g+17aa6MjY6Kj+gwnuFU/GL9yW0vylUsv3UptqyGDgu7rZj9MBqWD+kTeXCU6I/BcAV2KkYfJzfCiOZolHsl4aL/SiI3QgWwn5sIMshW5cjjhD0fwVm3vGH/jYZtrkOLLOllrd0lfrOqoJ7b5BGlRQCqHfues0nLIEKcSBF9WWMIzdTY/YRa6XW/LLZHPYvoh1WmNKQvTkqxgZNHAZP+BQ/6ErDXtvLQTF6u/in1CDE/8uTZEbm6VrX61ppdCLwgIQdmb+mNsDi/fFiLKPcIwa6PrysK6svhhM3wjVTuzsPfMFJanY8AJ+BqhDOYq/UG9FMDJ0kN/RjeVfMFjs/i9vilrS1yukWk+S+G9x2mbn5vkTnO68cCqdtKRRuwNZSavt1hwodTy9m8nRyg4OXZ5Cz81KRyh9JXkjX6bQQw4IRsDfcT9twjd+hDBvMv4ymob45wgvKszKCvPNeUzS4WPU1pX6/EUE6YrtzOH06xCGstP/QtS49Kmd1+T4sraS0X5Kqsk=
  - secure: KS19hxigx3P+EwRO6fhlPRuPOULyrAimI4R/jEWNtv1Eh/GWuwa8H+L5KDhWVwrQojrSkDB5ZB0YkLjwuy7DAWNq9yprXYdeAkc1iumCFtZnKNV1rwJ1FVh2y8PEeV8vFvx+17TyMXbtJIOkZWHo+1//tenqZGsz5JhkFyMYeuCKLSjvgHAXEaGOy3thdhxhTnYaATarq1R29uUOLBrR5lHZc1m36r8OrQ/NkZ+tI5fZToDoAjk5Zyx0m5m3EKZ4ejzVhoTnNjUlpwjKWX9uUVAD1Enhga6GYWr8rwxJJGf9UO0i/nBdDEThGk7dhEfnOcvBnM+ThXQsVFf/YHjA2ENI7RvTLl+6ItDEu9rDlyelJ+cBDgiCe4hoEk7k+wi5TEIx9PawXAxlYYsDu/0zRzGHVsgm9zXvirxiQ4vDMW3a3F+pA5myil+y8s23fAWHhdgxzONcAa3CZO894NML4dhWeupZ9Sv6e51PnPUthbBQpvx+J/Uws+9j/StAudD7LPrmUpvw6BHyU3UGaMC9/3XfW1oFMQ315N0f8si01Xtpeb8FHCNNtv1Cx9P3cDC9jW8TH9Ss8QfuO7DkK55SyPR3tZ8X34PSsAB99z9p/j8EYed41WHKcg3w8lFVOIf7XgVrcwq5fDKExIYkKroi7/JNivZFmhbxaukqjRuyUvs=
