package com.exsoinn.util.epf;

/**
 * Created by QuijadaJ on 5/5/2017.
 */
public class TestData {
    private TestData() {

    }

    public static final String verOrgXml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<VER_ORG xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n" +
            "\txmlns:schemaLocation=\"http://www.dnb.com/VER_ORG/Vers1/Rls4 conf/schema/VER_ORG_Vers1_Rls4.xsd\"\n" +
            "\txmlns:ns=\"http://www.dnb.com/VER_ORG/Vers1/Rls4\">\n" +
            "\t<SIGNONMSGSV1>\n" +
            "\t\t<SONMSG>\n" +
            "\t\t\t<DTCLIENT>20161109 14:28:52</DTCLIENT>\n" +
            "\t\t\t<LANGUAGE>331</LANGUAGE>\n" +
            "\t\t\t<APPID>IEDETRAD-19555</APPID>\n" +
            "\t\t\t<APPVER>0100</APPVER>\n" +
            "\t\t\t<STAT_NTFN>\n" +
            "\t\t\t\t<STAT_CD>0</STAT_CD>\n" +
            "\t\t\t</STAT_NTFN>\n" +
            "\t\t</SONMSG>\n" +
            "\t</SIGNONMSGSV1>\n" +
            "\t<VERORG_MSGSV1>\n" +
            "\t\t<VERORG_TRN>\n" +
            "\t\t\t<TRNUID>IEDETRAD-19555_20161109 14:28:52</TRNUID>\n" +
            "\t\t\t<STAT_NTFN>\n" +
            "\t\t\t\t<STAT_CD>0</STAT_CD>\n" +
            "\t\t\t</STAT_NTFN>\n" +
            "\t\t\t<VERORG_MSG>\n" +
            "\t\t\t\t<MTCH_RSLT>\n" +
            "\t\t\t\t\t<CAND_REF>\n" +
            "\t\t\t\t\t\t<DUNS_NBR>180921889</DUNS_NBR>\n" +
            "\t\t\t\t\t\t<REGN_STAT_CD>15201</REGN_STAT_CD>\n" +
            "\t\t\t\t\t\t<CAND_RNK>1</CAND_RNK>\n" +
            "\t\t\t\t\t\t<CFDC_LVL_VAL>10</CFDC_LVL_VAL>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_TEXT>AAAAAZAAFBA</MTCH_GRD_TEXT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12176</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>1</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12179</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>2</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12177</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>3</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12186</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>4</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12187</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>5</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12189</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>6</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12190</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>7</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12227</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>8</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12230</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>9</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12229</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>B</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>33</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>10</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12228</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>11</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_BASS_TEXT>0000000000980000000000009898</MTCH_BASS_TEXT>\n" +
            "\t\t\t\t\t\t<INDS_CODE>\n" +
            "\t\t\t\t\t\t\t<STD_INDS_CODE>48129901</STD_INDS_CODE>\n" +
            "\t\t\t\t\t\t\t<INDS_CODE_TYPE_CD>15361</INDS_CODE_TYPE_CD>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>50</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</INDS_CODE>\n" +
            "\t\t\t\t\t</CAND_REF>\n" +
            "\t\t\t\t\t<CAND_REF>\n" +
            "\t\t\t\t\t\t<DUNS_NBR>33538330</DUNS_NBR>\n" +
            "\t\t\t\t\t\t<REGN_STAT_CD>15200</REGN_STAT_CD>\n" +
            "\t\t\t\t\t\t<CAND_RNK>1</CAND_RNK>\n" +
            "\t\t\t\t\t\t<CFDC_LVL_VAL>4</CFDC_LVL_VAL>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_TEXT>BFFAAZZBFZF</MTCH_GRD_TEXT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12176</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>B</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>37</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>1</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12179</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>2</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12177</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>3</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12186</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>4</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12187</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>5</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12189</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>6</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12190</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>7</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12227</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>B</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>80</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>8</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12230</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>9</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12229</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>10</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12228</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>11</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_BASS_TEXT>0000000000989800000000989898</MTCH_BASS_TEXT>\n" +
            "\t\t\t\t\t\t<INDS_CODE>\n" +
            "\t\t\t\t\t\t\t<STD_INDS_CODE>99992222</STD_INDS_CODE>\n" +
            "\t\t\t\t\t\t\t<INDS_CODE_TYPE_CD>15361</INDS_CODE_TYPE_CD>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>50</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</INDS_CODE>\n" +
            "\t\t\t\t\t</CAND_REF>\n" +
            "\t\t\t\t\t<CAND_REF>\n" +
            "\t\t\t\t\t\t<DUNS_NBR>91407816</DUNS_NBR>\n" +
            "\t\t\t\t\t\t<REGN_STAT_CD>15200</REGN_STAT_CD>\n" +
            "\t\t\t\t\t\t<CAND_RNK>2</CAND_RNK>\n" +
            "\t\t\t\t\t\t<CFDC_LVL_VAL>4</CFDC_LVL_VAL>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_TEXT>FAAAAZZAFZZ</MTCH_GRD_TEXT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12176</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>1</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12179</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>2</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12177</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>3</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12186</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>4</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12187</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>5</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12189</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>6</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12190</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>7</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12227</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>8</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12230</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>9</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12229</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>10</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12228</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>11</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_BASS_TEXT>0000000000989800009800989898</MTCH_BASS_TEXT>\n" +
            "\t\t\t\t\t</CAND_REF>\n" +
            "\t\t\t\t\t<CAND_REF>\n" +
            "\t\t\t\t\t\t<DUNS_NBR>15109818</DUNS_NBR>\n" +
            "\t\t\t\t\t\t<REGN_STAT_CD>15201</REGN_STAT_CD>\n" +
            "\t\t\t\t\t\t<CAND_RNK>2</CAND_RNK>\n" +
            "\t\t\t\t\t\t<CFDC_LVL_VAL>6</CFDC_LVL_VAL>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_TEXT>AFFAAZFBFBA</MTCH_GRD_TEXT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12176</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>1</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12179</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>2</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12177</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>3</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12186</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>4</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12187</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>5</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12189</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>6</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12190</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>7</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12227</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>B</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>80</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>8</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12230</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>9</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12229</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>B</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>33</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>10</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12228</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>11</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_BASS_TEXT>0000000000980000000000009898</MTCH_BASS_TEXT>\n" +
            "\t\t\t\t\t\t<INDS_CODE>\n" +
            "\t\t\t\t\t\t\t<STD_INDS_CODE>59990600</STD_INDS_CODE>\n" +
            "\t\t\t\t\t\t\t<INDS_CODE_TYPE_CD>15361</INDS_CODE_TYPE_CD>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>50</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</INDS_CODE>\n" +
            "\t\t\t\t\t</CAND_REF>\n" +
            "\t\t\t\t\t<CAND_REF>\n" +
            "\t\t\t\t\t\t<DUNS_NBR>178854167</DUNS_NBR>\n" +
            "\t\t\t\t\t\t<REGN_STAT_CD>15201</REGN_STAT_CD>\n" +
            "\t\t\t\t\t\t<CAND_RNK>3</CAND_RNK>\n" +
            "\t\t\t\t\t\t<CFDC_LVL_VAL>5</CFDC_LVL_VAL>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_TEXT>AFFFAZZFFBA</MTCH_GRD_TEXT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12176</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>1</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12179</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>2</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12177</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>3</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12186</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>4</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12187</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>5</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12189</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>6</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12190</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>7</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12227</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>8</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12230</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>9</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12229</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>B</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>33</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>10</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12228</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>11</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_BASS_TEXT>0000000000989800000000009898</MTCH_BASS_TEXT>\n" +
            "\t\t\t\t\t\t<INDS_CODE>\n" +
            "\t\t\t\t\t\t\t<STD_INDS_CODE>48129901</STD_INDS_CODE>\n" +
            "\t\t\t\t\t\t\t<INDS_CODE_TYPE_CD>15361</INDS_CODE_TYPE_CD>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>50</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</INDS_CODE>\n" +
            "\t\t\t\t\t</CAND_REF>\n" +
            "\t\t\t\t\t<CAND_REF>\n" +
            "\t\t\t\t\t\t<DUNS_NBR>35208798</DUNS_NBR>\n" +
            "\t\t\t\t\t\t<REGN_STAT_CD>15200</REGN_STAT_CD>\n" +
            "\t\t\t\t\t\t<CAND_RNK>3</CAND_RNK>\n" +
            "\t\t\t\t\t\t<CFDC_LVL_VAL>3</CFDC_LVL_VAL>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_TEXT>BFFFAZZFFZF</MTCH_GRD_TEXT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12176</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>B</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>37</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>1</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12179</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>2</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12177</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>3</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12186</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>4</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12187</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>5</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12189</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>6</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12190</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>7</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12227</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>8</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12230</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>9</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12229</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>10</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12228</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>11</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_BASS_TEXT>0000000000989800000000989898</MTCH_BASS_TEXT>\n" +
            "\t\t\t\t\t\t<INDS_CODE>\n" +
            "\t\t\t\t\t\t\t<STD_INDS_CODE>99992222</STD_INDS_CODE>\n" +
            "\t\t\t\t\t\t\t<INDS_CODE_TYPE_CD>15361</INDS_CODE_TYPE_CD>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>50</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</INDS_CODE>\n" +
            "\t\t\t\t\t</CAND_REF>\n" +
            "\t\t\t\t\t<CAND_REF>\n" +
            "\t\t\t\t\t\t<DUNS_NBR>36815189</DUNS_NBR>\n" +
            "\t\t\t\t\t\t<REGN_STAT_CD>15200</REGN_STAT_CD>\n" +
            "\t\t\t\t\t\t<CAND_RNK>4</CAND_RNK>\n" +
            "\t\t\t\t\t\t<CFDC_LVL_VAL>3</CFDC_LVL_VAL>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_TEXT>BFFFAZZFBZF</MTCH_GRD_TEXT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12176</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>B</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>37</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>1</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12179</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>2</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12177</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>3</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12186</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>4</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12187</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>5</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12189</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>6</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12190</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>7</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12227</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>8</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12230</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>B</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>51</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>9</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12229</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>10</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12228</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>11</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_BASS_TEXT>0000000000989800000000989898</MTCH_BASS_TEXT>\n" +
            "\t\t\t\t\t\t<INDS_CODE>\n" +
            "\t\t\t\t\t\t\t<STD_INDS_CODE>99992222</STD_INDS_CODE>\n" +
            "\t\t\t\t\t\t\t<INDS_CODE_TYPE_CD>15361</INDS_CODE_TYPE_CD>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>50</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</INDS_CODE>\n" +
            "\t\t\t\t\t</CAND_REF>\n" +
            "\t\t\t\t\t<CAND_REF>\n" +
            "\t\t\t\t\t\t<DUNS_NBR>66763089</DUNS_NBR>\n" +
            "\t\t\t\t\t\t<REGN_STAT_CD>15200</REGN_STAT_CD>\n" +
            "\t\t\t\t\t\t<CAND_RNK>5</CAND_RNK>\n" +
            "\t\t\t\t\t\t<CFDC_LVL_VAL>2</CFDC_LVL_VAL>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_TEXT>FFFFAZFFBZF</MTCH_GRD_TEXT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12176</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>35</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>1</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12179</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>2</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12177</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>3</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12186</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>4</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12187</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>A</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>100</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>5</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12189</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>6</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12190</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>7</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12227</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>8</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12230</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>B</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>51</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>9</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12229</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>Z</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>-1</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>10</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_TYP_CD>12228</MTCH_GRD_CMPT_TYP_CD>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_RAT>F</MTCH_GRD_CMPT_RAT>\n" +
            "\t\t\t\t\t\t\t<MTCH_GRD_CMPT_SCR>0</MTCH_GRD_CMPT_SCR>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>11</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</MTCH_GRD_CMPT>\n" +
            "\t\t\t\t\t\t<MTCH_BASS_TEXT>0000000000980000000000989898</MTCH_BASS_TEXT>\n" +
            "\t\t\t\t\t\t<INDS_CODE>\n" +
            "\t\t\t\t\t\t\t<STD_INDS_CODE>79910000</STD_INDS_CODE>\n" +
            "\t\t\t\t\t\t\t<INDS_CODE_TYPE_CD>15361</INDS_CODE_TYPE_CD>\n" +
            "\t\t\t\t\t\t\t<DSPL_SEQ_NBR>50</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t</INDS_CODE>\n" +
            "\t\t\t\t\t</CAND_REF>\n" +
            "\t\t\t\t</MTCH_RSLT>\n" +
            "\t\t\t\t<PAYL_HDR>\n" +
            "\t\t\t\t\t<DUNS_NBR>000000000</DUNS_NBR>\n" +
            "\t\t\t\t\t<REGN_STAT_CD>15200</REGN_STAT_CD>\n" +
            "\t\t\t\t\t<GSRL_DT>2016-11-09T14:28:52</GSRL_DT>\n" +
            "\t\t\t\t\t<INFO_SRC_CD>13182</INFO_SRC_CD>\n" +
            "\t\t\t\t</PAYL_HDR>\n" +
            "\t\t\t\t<ORG_ID>\n" +
            "\t\t\t\t\t<REGN_NBR_ENTR>\n" +
            "\t\t\t\t\t\t<REGN_NBR>4891211129</REGN_NBR>\n" +
            "\t\t\t\t\t\t<REGN_NBR_CD>15336</REGN_NBR_CD>\n" +
            "\t\t\t\t\t\t<DNB_DATA_PRVD_CD>13182</DNB_DATA_PRVD_CD>\n" +
            "\t\t\t\t\t</REGN_NBR_ENTR>\n" +
            "\t\t\t\t</ORG_ID>\n" +
            "\t\t\t\t<SUBJ_DET />\n" +
            "\t\t\t\t<INTL_CTRL />\n" +
            "\t\t\t\t<BUS_NME>\n" +
            "\t\t\t\t\t<NME_ENTR>\n" +
            "\t\t\t\t\t\t<NME_CD>110</NME_CD>\n" +
            "\t\t\t\t\t\t<NME_ENTR_VW>\n" +
            "\t\t\t\t\t\t\t<NME_TEXT>LIFE TIME WIRELESS INC</NME_TEXT>\n" +
            "\t\t\t\t\t\t\t<LANG_CD>331</LANG_CD>\n" +
            "\t\t\t\t\t\t\t<FRMT_CD>0</FRMT_CD>\n" +
            "\t\t\t\t\t\t</NME_ENTR_VW>\n" +
            "\t\t\t\t\t\t<DNB_DATA_PRVD_CD>13182</DNB_DATA_PRVD_CD>\n" +
            "\t\t\t\t\t</NME_ENTR>\n" +
            "\t\t\t\t\t<NME_ENTR>\n" +
            "\t\t\t\t\t\t<NME_CD>110</NME_CD>\n" +
            "\t\t\t\t\t\t<NME_ENTR_VW>\n" +
            "\t\t\t\t\t\t\t<NME_TEXT>LIFE TIME WIRELESS INC.</NME_TEXT>\n" +
            "\t\t\t\t\t\t\t<LANG_CD>331</LANG_CD>\n" +
            "\t\t\t\t\t\t\t<FRMT_CD>0</FRMT_CD>\n" +
            "\t\t\t\t\t\t\t<STDN_APPL_CD>24099</STDN_APPL_CD>\n" +
            "\t\t\t\t\t\t</NME_ENTR_VW>\n" +
            "\t\t\t\t\t\t<DNB_DATA_PRVD_CD>13182</DNB_DATA_PRVD_CD>\n" +
            "\t\t\t\t\t</NME_ENTR>\n" +
            "\t\t\t\t\t<NME_ENTR>\n" +
            "\t\t\t\t\t\t<NME_CD>110</NME_CD>\n" +
            "\t\t\t\t\t\t<NME_ENTR_VW>\n" +
            "\t\t\t\t\t\t\t<NME_TEXT>LIFE TIME WIRELESS</NME_TEXT>\n" +
            "\t\t\t\t\t\t\t<LANG_CD>331</LANG_CD>\n" +
            "\t\t\t\t\t\t\t<FRMT_CD>0</FRMT_CD>\n" +
            "\t\t\t\t\t\t\t<STDN_APPL_CD>13135</STDN_APPL_CD>\n" +
            "\t\t\t\t\t\t</NME_ENTR_VW>\n" +
            "\t\t\t\t\t\t<DNB_DATA_PRVD_CD>13182</DNB_DATA_PRVD_CD>\n" +
            "\t\t\t\t\t</NME_ENTR>\n" +
            "\t\t\t\t</BUS_NME>\n" +
            "\t\t\t\t<BUS_ADR>\n" +
            "\t\t\t\t\t<ADR_ENTR>\n" +
            "\t\t\t\t\t\t<ADR_USG_CD>1114</ADR_USG_CD>\n" +
            "\t\t\t\t\t\t<ADR_ENTR_VW>\n" +
            "\t\t\t\t\t\t\t<ADR_LINE>\n" +
            "\t\t\t\t\t\t\t\t<TEXT>8007 FLATLANDS AVE</TEXT>\n" +
            "\t\t\t\t\t\t\t\t<DSPL_SEQ_NBR>2</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t\t</ADR_LINE>\n" +
            "\t\t\t\t\t\t\t<POST_TOWN>BROOKLYN</POST_TOWN>\n" +
            "\t\t\t\t\t\t\t<POST_CODE>11236</POST_CODE>\n" +
            "\t\t\t\t\t\t\t<TERR>NY</TERR>\n" +
            "\t\t\t\t\t\t\t<GEO_REF_ID>1073</GEO_REF_ID>\n" +
            "\t\t\t\t\t\t\t<LANG_CD>331</LANG_CD>\n" +
            "\t\t\t\t\t\t</ADR_ENTR_VW>\n" +
            "\t\t\t\t\t\t<DNB_DATA_PRVD_CD>13182</DNB_DATA_PRVD_CD>\n" +
            "\t\t\t\t\t</ADR_ENTR>\n" +
            "\t\t\t\t\t<ADR_ENTR>\n" +
            "\t\t\t\t\t\t<ADR_USG_CD>1114</ADR_USG_CD>\n" +
            "\t\t\t\t\t\t<ADR_ENTR_VW>\n" +
            "\t\t\t\t\t\t\t<STDN_APPL_CD>13135</STDN_APPL_CD>\n" +
            "\t\t\t\t\t\t\t<STR_NBR>8007</STR_NBR>\n" +
            "\t\t\t\t\t\t\t<STR_NME>FLATLANDS</STR_NME>\n" +
            "\t\t\t\t\t\t\t<STR_TYP_TEXT>AVE</STR_TYP_TEXT>\n" +
            "\t\t\t\t\t\t\t<POST_TOWN>BROOKLYN</POST_TOWN>\n" +
            "\t\t\t\t\t\t\t<POST_CODE>11236</POST_CODE>\n" +
            "\t\t\t\t\t\t\t<POST_CODE_EXTN>3533</POST_CODE_EXTN>\n" +
            "\t\t\t\t\t\t\t<TERR>NY</TERR>\n" +
            "\t\t\t\t\t\t\t<GEO_REF_ID>1073</GEO_REF_ID>\n" +
            "\t\t\t\t\t\t\t<LANG_CD>331</LANG_CD>\n" +
            "\t\t\t\t\t\t</ADR_ENTR_VW>\n" +
            "\t\t\t\t\t\t<STD_STRG_VW>\n" +
            "\t\t\t\t\t\t\t<STD_STR_LINE>\n" +
            "\t\t\t\t\t\t\t\t<TEXT>8007 FLATLANDS AVENUE</TEXT>\n" +
            "\t\t\t\t\t\t\t\t<DSPL_SEQ_NBR>1</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t\t</STD_STR_LINE>\n" +
            "\t\t\t\t\t\t\t<STD_RGN_LINE>\n" +
            "\t\t\t\t\t\t\t\t<TEXT>BROOKLYN NY 11236-3533</TEXT>\n" +
            "\t\t\t\t\t\t\t\t<DSPL_SEQ_NBR>1</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t\t</STD_RGN_LINE>\n" +
            "\t\t\t\t\t\t\t<LANG_CD>331</LANG_CD>\n" +
            "\t\t\t\t\t\t\t<STDN_APPL_CD>13135</STDN_APPL_CD>\n" +
            "\t\t\t\t\t\t</STD_STRG_VW>\n" +
            "\t\t\t\t\t\t<DNB_DATA_PRVD_CD>13182</DNB_DATA_PRVD_CD>\n" +
            "\t\t\t\t\t</ADR_ENTR>\n" +
            "\t\t\t\t\t<ADR_ENTR>\n" +
            "\t\t\t\t\t\t<ADR_USG_CD>1114</ADR_USG_CD>\n" +
            "\t\t\t\t\t\t<ADR_ENTR_VW>\n" +
            "\t\t\t\t\t\t\t<STDN_APPL_CD>24099</STDN_APPL_CD>\n" +
            "\t\t\t\t\t\t\t<STR_NBR>8007</STR_NBR>\n" +
            "\t\t\t\t\t\t\t<STR_NME>FLATLANDS</STR_NME>\n" +
            "\t\t\t\t\t\t\t<STR_TYP_TEXT>AVE</STR_TYP_TEXT>\n" +
            "\t\t\t\t\t\t\t<MINR_TWN_NME>BROOKLYN</MINR_TWN_NME>\n" +
            "\t\t\t\t\t\t\t<POST_TOWN>BROOKLYN</POST_TOWN>\n" +
            "\t\t\t\t\t\t\t<POST_CODE>11236</POST_CODE>\n" +
            "\t\t\t\t\t\t\t<POST_CODE_EXTN>3533</POST_CODE_EXTN>\n" +
            "\t\t\t\t\t\t\t<CNTY>KINGS</CNTY>\n" +
            "\t\t\t\t\t\t\t<TERR>NY</TERR>\n" +
            "\t\t\t\t\t\t\t<GEO_REF_ID>1073</GEO_REF_ID>\n" +
            "\t\t\t\t\t\t\t<LANG_CD>331</LANG_CD>\n" +
            "\t\t\t\t\t\t</ADR_ENTR_VW>\n" +
            "\t\t\t\t\t\t<STD_STRG_VW>\n" +
            "\t\t\t\t\t\t\t<STD_STR_LINE>\n" +
            "\t\t\t\t\t\t\t\t<TEXT>8007 FLATLANDS AVENUE</TEXT>\n" +
            "\t\t\t\t\t\t\t\t<DSPL_SEQ_NBR>1</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t\t</STD_STR_LINE>\n" +
            "\t\t\t\t\t\t\t<STD_RGN_LINE>\n" +
            "\t\t\t\t\t\t\t\t<TEXT>BROOKLYN NY 11236-3533</TEXT>\n" +
            "\t\t\t\t\t\t\t\t<DSPL_SEQ_NBR>1</DSPL_SEQ_NBR>\n" +
            "\t\t\t\t\t\t\t</STD_RGN_LINE>\n" +
            "\t\t\t\t\t\t\t<LANG_CD>331</LANG_CD>\n" +
            "\t\t\t\t\t\t\t<STDN_APPL_CD>24099</STDN_APPL_CD>\n" +
            "\t\t\t\t\t\t</STD_STRG_VW>\n" +
            "\t\t\t\t\t\t<DNB_DATA_PRVD_CD>13182</DNB_DATA_PRVD_CD>\n" +
            "\t\t\t\t\t</ADR_ENTR>\n" +
            "\t\t\t\t</BUS_ADR>\n" +
            "\t\t\t\t<TLCM_INFO>\n" +
            "\t\t\t\t\t<TLCM_ENTR>\n" +
            "\t\t\t\t\t\t<TEL_NBR_CD>1110</TEL_NBR_CD>\n" +
            "\t\t\t\t\t\t<TEL_NBR>7184441216</TEL_NBR>\n" +
            "\t\t\t\t\t\t<GEO_REF_ID>1073</GEO_REF_ID>\n" +
            "\t\t\t\t\t\t<TLCM_ENTR_VW>\n" +
            "\t\t\t\t\t\t\t<INFO_FRMT_CD>15199</INFO_FRMT_CD>\n" +
            "\t\t\t\t\t\t\t<STDN_APPL_CD>13135</STDN_APPL_CD>\n" +
            "\t\t\t\t\t\t\t<TEL_NBR_CD>1110</TEL_NBR_CD>\n" +
            "\t\t\t\t\t\t\t<TEL_NBR>7184441216</TEL_NBR>\n" +
            "\t\t\t\t\t\t</TLCM_ENTR_VW>\n" +
            "\t\t\t\t\t\t<TLCM_ENTR_VW>\n" +
            "\t\t\t\t\t\t\t<INFO_FRMT_CD>15199</INFO_FRMT_CD>\n" +
            "\t\t\t\t\t\t\t<STDN_APPL_CD>24099</STDN_APPL_CD>\n" +
            "\t\t\t\t\t\t\t<TEL_NBR_CD>1110</TEL_NBR_CD>\n" +
            "\t\t\t\t\t\t\t<TEL_NBR>7184441216</TEL_NBR>\n" +
            "\t\t\t\t\t\t</TLCM_ENTR_VW>\n" +
            "\t\t\t\t\t\t<DNB_DATA_PRVD_CD>13182</DNB_DATA_PRVD_CD>\n" +
            "\t\t\t\t\t</TLCM_ENTR>\n" +
            "\t\t\t\t</TLCM_INFO>\n" +
            "\t\t\t\t<ACTV />\n" +
            "\t\t\t\t<PRIN_MGMT />\n" +
            "\t\t\t</VERORG_MSG>\n" +
            "\t\t</VERORG_TRN>\n" +
            "\t</VERORG_MSGSV1>\n" +
            "</VER_ORG>";
}
